volumes:
  pgdata:

services:
  db:
    image: postgres
    #restart: unless-stopped

    environment:
      POSTGRES_PASSWORD: toor123
      POSTGRES_USER: playground
      POSTGRES_DB: playground
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432

    volumes:
      - pgdata:/var/lib/postgresql/data

